### ISSUE TITLE
Guardian Node Votes Being ignored 

### ISSUE THREAD

**Issue by MichaelSaintJohn** [thetatoken/guardian-mainnet-guide#109]
@LL244 hello mate. Has your issue been resolved?

**Comment by MichaelSaintJohn** [comment]
@LL244 hello mate. Has your issue been resolved?

**Comment by LL244** [comment]
Thank you.
Currently, there is an improvement.
In the past, the problem appeared after a week or so, so I'll have to wait and see.

I tested various things for a few days with Gpool and my nodes.
Setting the Performance Tier to Premium improved the network stability.
The probability of validation failures increases when the Tier is standard, and validation tends to fail when the Guardian Peers are low.
The old version of the Guardian node tended to be more stable when the Tier was lower. 
However, in the current version, it may be more stable when the Tier is higher. 
Several possibilities may contribute as factors (the change of network size, validation situation, etc.) 
I would like to see the official best setting conditions.

The procedure this time is as follows.
delete DB and snapshot
reinstall guardian node app
restart OS(windows10)
unstake
restake
Tier > Premium (Possibly a blind spot in that the standard Tier is the best.)

**Comment by LL244** [comment]
Resolved, please close ticket.
