### ISSUE TITLE
Guardian Node Synchronisation Issue 

### ISSUE THREAD

**Issue by ThetaNetworkSupport** [thetatoken/guardian-mainnet-guide#216]
Hello @greer3 , Sorry to hear that you're still having issues synchronising your Guardian Node, kindly join the telegram group and contact the Theta Network Support on Telegram via the weblink https://t.me/thetanetworking
They'll be happy to resolve your issue with a guide on how to go about it. Cheers.

**Comment by greer3** [comment]
I am having trouble finding my guardian node.  It has vanished from my computer. That’s a first.  My account with 12 words trying to get it going again without seeing a way to get it done. A reset  password does not coplete sending to my email for the reset password.  I also several weeks ago staked 10k tfuel without seeing it posted in my account.   I would appreciate your help.
Greer Evans
