### ISSUE TITLE
BIG problem with stacking and withdraw

### ISSUE THREAD

**Issue by rety21** [thetatoken/guardian-mainnet-guide#22]
Hello! I need help with stacking and withdraw. I wanted to test the system before making an investment so i deposited 1004 theta in a stake. Afther everything went well, i wanted to test the withdraw before i could make a real deposit. I made the same process with the withdraw option in the same theta wallet i used to deposit, the guardian node is now "out of operation" because the withdraw but the wallet balance does not show the withdawn thetas. Even worse, is that if i go to the guardian adress explorer, it shows the 1004 deposit, an out "0 theta" withdraw transaction "finalized", and a "0 theta" balance. Where are the 1004 thetas? Shall i wait?

**Comment by rety21** [comment]
More info, the "RAW TXN" shows:

"root":{
"hash":"XXXXXX(the hash)"
"type":9
"data":{
"fee":{
"thetawei":"0"
"tfuelwei":"1000000000000"
}
"source":{
"address":"XXXXXXX(my adress)"
"coins":{
"thetawei":"0"                       ///// does not the amout be here??
"tfuelwei":"0"

**Comment by jieyilong** [comment]
By design there is a pending withdrawal period of 28800 blocks. The staked Theta will return to your wallet 28800 blocks (roughly 50 hours) after you withdraw your stake. Hope this helps.

**Comment by rety21** [comment]
> By design there is a pending withdrawal period of 28800 blocks. The staked Theta will return to your wallet 28800 blocks (roughly 50 hours) after you withdraw your stake. Hope this helps.

Thanks for the reply but alredy passed more than 50 hours and nothing changed :/
The question is, ¿why the amount of the withdrawal transaction is zero? Is it possible a failure like that in the code?

**Comment by rety21** [comment]
> By design there is a pending withdrawal period of 28800 blocks. The staked Theta will return to your wallet 28800 blocks (roughly 50 hours) after you withdraw your stake. Hope this helps.

@jieyilong Well yes, after about 60hours the Thetas are in my account. The transaction still shows 0 Thetas but the balance is right. Thank you!
