### ISSUE TITLE
Guardian Node Snapshot seems to miss metadata?

### ISSUE THREAD

**Issue by convernaticspeter** [thetatoken/guardian-mainnet-guide#29]
Hi there,

was following this: https://github.com/thetatoken/theta-mainnet-integration-guide/blob/master/docs/mainnet.md

When trying to start the node, I get a fatal error.
FATA[0022] Snapshot validation failed, err: Failed to load snapshot metadata, rlp: too few elements for core.SnapshotFirstBlock, decoding into (core.SnapshotMetadata).ProofTrios[1].First

Seems like the Snapshot under https://mainnet-data.thetatoken.org/snapshot causes issues?

I'm running Ubuntu 20.04 with CLI on a root Server. 

Thanks for any help!

**Comment by jieyilong** [comment]
We have just tested the latest snaphsot, and it was loaded successfully. Do you mind give it another try? Thanks
