### ISSUE TITLE
Syncing Theta Wallet stuck at 99.99% for hours...

### ISSUE THREAD

**Issue by juliancedrone** [thetatoken/guardian-mainnet-guide#35]
Hello I have been trying to get my Theta Guardian Node to sync and it has been stuck on 99.99% for almost a day! It is currently stuck at (8,707,199 / 8,708,451) and nothing I do will work. I have tried to delete the node database and it didn't work. I even tried to delete the key and it won't even let me do that. When I uninstall the Theta Guardian application and re-install it doesn't even ask me to do a fresh install or bring me to the application welcome screen where I can choose a install directory, even after reinstalling it just immediately goes back to trying to sync the node and doesn't even give me the option of a fresh install. Please if anyone could help I would be greatly appreciative.

**Comment by spiralnova** [comment]
Try resetting the database and changing the performance to Standard.
https://github.com/thetatoken/guardian-mainnet-guide/issues/28#issuecomment-753655539

**Comment by juliancedrone** [comment]
Resetting the database did not work for me. I had to manually go in and delete everything from %appdata% then re-install. Changing from Platinum to Standard seemed to work for me after completely deleting all data from %appdata%

**Comment by stevenstc** [comment]
thanks for the info
