### ISSUE TITLE
Not able to do fresh install of Guardian Node

### ISSUE THREAD

**Issue by juliancedrone** [thetatoken/guardian-mainnet-guide#37]
I tried to uninstall and do a fresh install of the theta guardian node, however when I uninstalled and attempted to re-install it never brought me to the installation welcome page where I can create a new node and select a directory to install to, it just automatically tries to sync and never allows me to create a new node. I've tried to delete ALL files related to theta off my pc but somehow it still will not let me do a fresh install... can anyone please help?

**Comment by spiralnova** [comment]
Have you tried deleting the node database and node key from within the app?

**Comment by juliancedrone** [comment]
Resetting the database did not work for me. I had to manually go in and delete everything from %appdata% then re-install. Changing from Platinum to Standard seemed to work for me after completely deleting all data from %appdata%

Deleting node database and node key from within app did NOT work. I had to delete everything from Theta in the %appdata% folder.
