### ISSUE TITLE
I don't get it.  

### ISSUE THREAD

**Issue by kcsf** [thetatoken/guardian-mainnet-guide#38]
I want to contribute.  I installed the windows client, and followed as many directions as I could find online.
As soon as the app finishes loading - it's shows me the Deposit Stake screen.  If I try to do that following these instructions: https://github.com/thetatoken/guardian-mainnet-guide/blob/master/docs/STAKING.md#staking-through-web-wallet

it's impossible - as there is no Theta in my account "Invalid amount. Must be at least 1,000 THETA"

..so, I can't complete the setup process of the guardian app?

What am I missing here?

ps. If you guys want larger adoption of your platform - you really need to provide user-friendly instructions to people (like me) that don't know a hellofalottabout how crypto staking/etc. works.

**Comment by averytt** [comment]
@kcsf staking Theta is required if you would like to run a Guardian Node to help protect the network. You might be interested in the [Theta Edge Node](https://docs.thetatoken.org/docs/setup-theta-edge-node) which does not require staking to contribute.

Also, please check out the docs site which has all of Theta's concepts and projects documented: https://docs.thetatoken.org/

**Comment by kcsf** [comment]
How do I stake Theta?  Do I have to buy theta first?  That seems like an odd way to encourage users to volunteer their machines/bandwidth.
