### ISSUE TITLE
How to Move Unstaked Theta Tokens from a Guardian Node Account Address on a Laptop

### ISSUE THREAD

**Issue by SCpatriot** [thetatoken/guardian-mainnet-guide#58]
Wondering if anyone can help me. I run a Guardian Node (GN) from my laptop. I sent additional tokens from my wallet to my GN address thinking this would automatically boost my stake. When I click on the GN address on my laptop, my GN account comes up and shows the recently added tokens as a Balance in the Account Detail section. My stake is unchanged. At the bottom of the page in the Export Transaction History, my recently sent tokens appear as a Transfer. The other transaction in this section is my original Deposit Stake. I don't see a send/receive function to move these tokens out of the GN address to restake properly. Anyone have any idea how to fix this??
I ended up withdrawing my stake, and my original Token deposit was returned to my wallet, but the additional Tokens still remain as a Balance in the Account Detail section of the GN address with no obvious way to send them back to my wallet. Please help!!

**Comment by carl193352** [comment]
Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink www.t.me/thethetanetwork. They'll be happy to resolve your issue. Cheers.

**Comment by SCpatriot** [comment]
All is well. I emailed support@thetatoken.org and described my issue as above. They replied within an hour saying they would review my issue, and sent me a FAQ list. My issue was on the list. I was able to resolve the issue 100% with my son's basic  computer knowledge within 15 mins.
