### ISSUE TITLE
GN Failed to connect to the db

### ISSUE THREAD

**Issue by GitHinse** [thetatoken/guardian-mainnet-guide#74]
I just staked my first tokens and it's as if my node keeps on forcing restart with similar results every time. Tried deleted db reseting peers and downgrade to standard. Any idea what I might be missing ?

**Comment by Edwards6432** [comment]
Hello Mate, Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink www.t.me/thesupporttheta. They'll be happy to resolve your issue. Cheers.

**Comment by Edwards6432** [comment]
Hi, I think that's the old telegram support. Attached is the link for the new Telegram support, www.t.me/thesupportio. Sorry for the confusion

**Comment by ONealEdwards** [comment]
Have you got the discord app ? If you dont have one, set it up and join the theta group Discord community https://discord.gg/QfMpeZBfKB
