### ISSUE TITLE
Theta tokens missing, unlocked Keystore AND Nmemonic passphrase

### ISSUE THREAD

**Issue by turtlestryden** [thetatoken/guardian-mainnet-guide#8]
If this is the wrong place to post this, please direct me to the correct place.  New user and not understanding the problem.  
I just got 10,000 theta tokens onto wallet.theta.org (unlocked wallet), went to the stake tab and deposited stake (entire amount) to the Gpool GN Holder (summary) and saw the quantity reside in this tab.  That was 8 hours ago.  This morning, the wallet.thetatoken.org page is empty, no sign of the previously listed transactions, tokens or Tfuel. 

I've imported the keystore (although I first exported it when the wallet was empty) and then I tried entering the mnemonic 12 words. My understanding is that the tokens should still be on the blockchain and not lost, as I didn't transfer the sum out - delegating in done without moving the tokens off the wallet?

Please advise @jieyilong @weiribao @weslevitt  , much appreciated

**Comment by juliancedrone** [comment]
What ended up happening? Did you ever regain access to your staked funds?

**Comment by turtlestryden** [comment]
Turned out to be either an update or something was going on with the network and I was plain unaware.  Funds re-appeared a few hours later, Youtubers talking about this problem also helped.
