### ISSUE TITLE
Respecto a Tfuel ganados

### ISSUE THREAD

**Issue by metafisica3** [thetatoken/guardian-mainnet-guide#83]
Buenas tardes,
Mi nodo esta trabajando bien, pero no me esta generando tfuel desde hace 2 dias, es decir sigo teniendo el mismo saldo en ( staker' balance ).
Quisiera saber a que se debe.
Volvi a reiniciar el nodo y solo genero 12 tfuel y luego ya no genero.

![saldo de staking](https://user-images.githubusercontent.com/80740083/111372304-14dde180-8660-11eb-8835-07c9bb8a510e.PNG)

**Comment by DavidGarry7654** [comment]
@metafisica3 Hola amigo, Lamento escuchar tu problema, puedes ponerte en contacto con el soporte de Theta Network en Telegram a través del enlace web https://t.me/thetanetworking. Estarán encantados de resolver su problema. Salud.
