### ISSUE TITLE
Unstake Pending withdrawl for over 48 hrs now

### ISSUE THREAD

**Issue by phyx1u5** [thetatoken/guardian-mainnet-guide#84]
Hi All

My guardian node recently went down and I had to unstake my Theta. However its been over 48hrs now and the status of my withdrawl still says Pending. Anyone have a similar issue?

**Comment by Garitty7612** [comment]
What version of GN were you running on ?
Also you should have received your unstaked theta already

**Comment by phyx1u5** [comment]
Im using Linux CLI version. I had to reinstall my GN because I was getting syncing errors. But now im trying to get my Theta off my old address and on to the new one.

However looking at previous posts, they mentioned to look at the block height which my theta will be returned to me and we have not quite hit that block height yet. Will update again if my theta is returned once the return height is hit.

**Comment by phyx1u5** [comment]
theta has been successfully returned to my wallet, just had to wait a few more hours
