### ISSUE TITLE
Guardian node stake changes

### ISSUE THREAD

**Issue by Mojo131313** [thetatoken/guardian-mainnet-guide#85]
I have a guardian node and am staking Theta, but the Stake value showing on the node regularly goes from the value of Theta I am staking to zero and then back again. Are my staked Theta at risk or does this mean that I wont be able to earn TFUEL on my node?

**Comment by Garitty7612** [comment]
What version of GN Are You Running on ?

**Comment by Mojo131313** [comment]
I'm running version 2.2.10. Been running it for a week now after issues getting it synched so dropped the Performance Tier to Standard. Earned nothing on it thus far either.

**Comment by Garitty7612** [comment]
Sorry to hear about your issue, you can contact Theta Network Support on Telegram via the weblink https://t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by Garitty7612** [comment]
@Mojo131313 Have you contacted Theta telegram support via www.t.me/thetanetworking

**Comment by Mojo131313** [comment]
I'll try that, thanks.
