### ISSUE TITLE
Guardian Node votes being ignored

### ISSUE THREAD

**Issue by cwild95** [thetatoken/guardian-mainnet-guide#89]
I setup my first guardian node two days ago. Since then I have only seen one tfuel payout, it's been approx 48 hours, and 24 since the first and only payout.

I keep seeing this error in my logs 
[2021-03-25 10:10:19]  WARN [consensus] Ignoring invalid vote err=Result{code:100000, message:Signature verification failed}

This makes me believe my node is not working correctly or generating tfuel. 
Has anyone else seen this issue? Any suggestions? 

I'm running the thetacli on macmini i7 16gb ram. 256gb ssd, 1gig fiber connection.

**Comment by cwild95** [comment]
Version 2.2.0 783f0c5fe3e05baf9483b11cef7732f28c05e46f
Built at Mon Mar  1 18:39:40 UTC 2021

**Comment by cwild95** [comment]
Yeah I'm not clicking that link. I see you have other deleted comments in other issues. gtfo of here with your phishing.

**Comment by nexster** [comment]
I have no Tfuel for 13 days now.

**Comment by LL244** [comment]
I have the same problem.
I'm not getting paid properly from Guardian node.
I'm having a lot of trouble. Who should I contact for help?

**Comment by nexster** [comment]
I fought this for a month.  Just stake to gpool.  It’s safe because staked theta can only be returned to Wallet that staked it.

**Comment by cwild95** [comment]
Sorry I should have closed this ticket. My GN is paying out as usual. View pending profits on guardianmonitor.io with 1k theta staked comes out to just over 1 tfuel a day. 

I don't want to use gpool as its a centralized location and kindof defeats the purpose of p2p content sharing.
