### ISSUE TITLE
Staking issue

### ISSUE THREAD

**Issue by joelmorgangreen** [thetatoken/guardian-mainnet-guide#97]
Hi, 
My guardian node is stuck at 99.76%. I know I can speed things up by deleting the node database and restarting the node, but does that delete my rewarded tfuel? 
And also, when do you receive that tfuel? I've heard every 8 days and I've heard at the end of the month...

**Comment by Lionel2298** [comment]
Hello Mate, Sorry to hear about your issue, you can contact the Theta Network Support on Telegram via the weblink www.t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by joelmorgangreen** [comment]
Does anyone know if this is legit? ^
If so, sorry Lionel, have seen some scammers, don't want to download stuff I don't know.

**Comment by Lionel2298** [comment]
Hello Mate, Sorry to hear about your issue, you can contact the Theta Network Support on Telegram via the weblink www.t.me/thetanetworking. They'll be happy to resolve your issue. Cheers.

**Comment by joelmorgangreen** [comment]
Affraid to download stuff I don't know, and have heard a lot about scammers on telegram. Does anyone know if you lose your tfuel if you delete your database?

**Comment by Lionel2298** [comment]
You’re not downloading anything. It’s the weblink for the telegram group chat

**Comment by joelmorgangreen** [comment]
Cheers, will check over there

**Comment by joelmorgangreen** [comment]
THIS IS A SCAM! WATCH OUT FOR SCAMMERS ON TELEGRAM. THETA IS NOT ON TELEGRAM!

**Comment by CryptoLoserz** [comment]
> THIS IS A SCAM! WATCH OUT FOR SCAMMERS ON TELEGRAM. THETA IS NOT ON TELEGRAM!

theta isnt real?
